@startuml

start

: Payer (#365.12);
: Insurance Company (#36);
: Group Insurance Plan (#355.3);
split
    : Insurance Type (#2.312);
    : Patient (#2);
split again
    :Plan Coverage Limitations (#355.32);
end split
stop

@enduml
